### ISSUE TITLE
curseq is GTCTTGTTGTTGGGCTTG of type BioSequences.BioSequence{BioSequences.DNAAlphabet{2}}

### ISSUE THREAD

**Issue by rfara** [timbitz/Whippet.jl#110]
Problem:

The line of code:

`println("curseq is ", curseq, " of type ", typeof(curseq))`

seems to print every seed sequence in the terminal:

`curseq is GTCTTGTTGTTGGGCTTG of type BioSequences.BioSequence{BioSequences.DNAAlphabet{2}}`

When I run a whippet-quant job on my cluster, the logfile becomes absolutely enormous. Maybe this also slows things down - I have no idea.

Solution:

Comment out/remove line 170 of src/align.jl.

I fixed the issue for myself by just commenting the line out. Maybe this will have some catastrophic issue. If so, please let me know!

**Comment by timbitz** [comment]
@rfara thanks for reporting-- looks like a debugging line left over from @gmassman, commenting out is correct.  I'll also look into #111, and push fixes for the v1.5 release.

**Comment by timbitz** [comment]
Fixed in master as of #113
