### ISSUE TITLE
Where is "graph.jls"?

### ISSUE THREAD

**Issue by justinjisu** [timbitz/Whippet.jl#127]
Hi Tim,

I'm currently trying to build a bam supplemented index; however, I'm getting the following error code: 
ERROR: LoadError: SystemError: opening file "~/Whippet.jl/bin/../index/graph.jls": No such file or directory

Is there supposed to be an index/graph.jls file or is this produced during index generation? How can I correct this error?

Thank you in advance!

**Comment by timbitz** [comment]
@justinjisu graph.jls is the index that you need to build by running whippet-index.jl.  It is output, not input that is missing-- the default is trying to write to a folder /index/ that you haven't created. Try specifying the output name with -x/--index

**Comment by justinjisu** [comment]
Thank you! That solved my problems.
