### ISSUE TITLE
jnc read count

### ISSUE THREAD

**Issue by BeatrizdeToledo** [timbitz/Whippet.jl#129]
Good morning, 

 am using whippet and I want to understand the read_count collumn in the .jnc file. I am comparing the values i obtained with SJ.out.tab of STAR. Are these the whippet raw read counts or are they normalized? I don't understand how a splice junction can have 0.1604707 read counts if it is not normalized.
Also, the values are quite different from the STAR and whippet files
Star - collumn V7 number of uniquely mapping reads crossing the junction
V1 V2 V3 V4 V5 V6 V7 V8 V9
9 78480421 78480510 2 4 1 26795 54 50

Whippet
CHROM DONOR_COORD ACCEPTOR_COORD GENEID.NODES.TYPE READCOUNT STRAND
9 78480420 78480511 PB.12851:7-9:ALT_ANNO 4603.964 -

in whippet, for index i used b) Annotation (GTF) + Alignment (BAM) supplemented index. --bam-min-reads 10, on quantify i used --biascorrect

**Comment by timbitz** [comment]
Hi-- Did you try turning off `--biascorrect` to get the raw counts (non bias-corrected)?

**Comment by timbitz** [comment]
Closing as I assume this solves the issue.
