### ISSUE TITLE
Fastq.gz files from different lanes

### ISSUE THREAD

**Issue by shregeno8** [timbitz/Whippet.jl#132]
I have paired-end Fastq files run on 2 lanes.
I am getting an error when I try to run whippet-quant.jl 

My command is
 `julia bin/whippet-quant_1.jl  ${SAMPLE}_L001_R1_001.fastq.gz,${SAMPLE}_L002_R1_001.fastq.gz ${SAMPLE}_L001_R2_001.fastq.gz,${SAMPLE}_L002_R2_001.fastq.gz --out Whippet/results/${SAMPLE}`

but this doesn't work.

What is the right command ?

**Comment by timbitz** [comment]
You have to merge the fastq files manually first, as with most programs.
