### ISSUE TITLE
Issue with ArgParse

### ISSUE THREAD

**Issue by zoescherzer0318** [timbitz/Whippet.jl#133]
I cannot seem to get Whippet to work, and it keeps outputting an error saying it cannot access ArgParse even though I made sure this module is in my .julia/v0.6 directory. I opened the julia RPL within the .julia/v0.6 directory and did Pkg.add("ArgParse") just to make sure, yet the same error is still being thrown (below).

Tue Aug 16 15:22:25 EDT 2022
Working directory is /blue/ewang/zoejstar/libZJS
module add julia/0.6.4
 cd /blue/ewang/zoejstar/.julia/v0.6/Whippet/
 julia /blue/ewang/zoejstar/.julia/v0.6/Whippet/bin/whippet-quant.jl /blue/ewang/zoejstar/NIH3T3/fasta_files/SRR1816794_1.fastq.gz -o /blue/ewang/zoejstar/NIH3T3/whippet_output/3T3_1 -x /blue/ewang/zoejstar/.julia/v0.6/Whippet/index/mm10.jls
Whippet v0.11.1 loading and compiling...
ERROR: LoadError: ArgumentError: Module ArgParse not found in current path.
Run `Pkg.add("ArgParse")` to install the ArgParse package.
Stacktrace:
 [1] _require(::Symbol) at ./loading.jl:435
 [2] require(::Symbol) at ./loading.jl:405
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] process_options(::Base.JLOptions) at ./client.jl:305
 [6] _start() at ./client.jl:371
while loading /blue/ewang/zoejstar/.julia/v0.6/Whippet/bin/whippet-quant.jl, in expression starting on line 10
===== module add julia/0.6.4
 cd /blue/ewang/zoejstar/.julia/v0.6/Whippet/
 julia /blue/ewang/zoejstar/.julia/v0.6/Whippet/bin/whippet-quant.jl /blue/ewang/zoejstar/NIH3T3/fasta_files/SRR1816794_1.fastq.gz -o /blue/ewang/zoejstar/NIH3T3/whippet_output/3T3_1 -x /blue/ewang/zoejstar/.julia/v0.6/Whippet/index/mm10.jls finished =====
runWhippet.30757.1660677721.7399876.out (END)

**Comment by timbitz** [comment]
Hi @zoescherzer0318 -- This honestly looks like it could be an issue with your cluster and module loading.  Did you try opening the REPL and typing 'using ArgParse' or 'using Whippet' ?

**Comment by timbitz** [comment]
Also Julia 0.6.4 is not really supported for this package anymore, you should be using the Long term support release 1.6.7

**Comment by timbitz** [comment]
And you should be using Whippet version 1.6.  I'm going to close this issue, as I'm not going to debug a long-deprecated release.
