### ISSUE TITLE
ERROR: LoadError: SystemError: opening file "/home/emanuele/Whippet.jl/bin/../index/graph.jls": No such file or directory

### ISSUE THREAD

**Issue by emanueleraggi** [timbitz/Whippet.jl#134]
Hello, I am following the procedure to install Whippet.jl on the [official repo](https://github.com/timbitz/Whippet.jl/tree/master). 
As I go ahead and compile the project it stops throwing the following error: 

`ERROR: LoadError: SystemError: opening file "/home/emanuele/Whippet.jl/bin/../index/graph.jls": No such file or directory`

Now, if you go the available files in the [official repo](https://github.com/timbitz/Whippet.jl/tree/master) there is no such directory. 
It looks like that the `/index/graph.jls` is not in the github. Unless that has to be created somewhere else?

How do I solve that? Thanks for any advise everyone.

**Comment by timbitz** [comment]
Hi @emanueleraggi -- Did you try following the documentation?  You have to build an index.

**Comment by Oliverfeudj** [comment]
Good Morning @timbitz 
I am facing the same error when I run `julia bin/whippet-index.jl --fasta hg19.fa.gz --gtf anno/gencode_hg19.v25.tsl1.gtf.gz`
to get the index.
Do you have any clue where it might come from, please?
Thank you for your help

**Comment by timbitz** [comment]
You can use the -x command to specify the location/name of the saved index

**Comment by esmagamze** [comment]
I have also the same problem. Could you write code for how to fix it.
