### ISSUE TITLE
graph.jls

### ISSUE THREAD

**Issue by AndrewLangvt** [timbitz/Whippet.jl#53]
Hey @timbitz, 

Currently, whippet is installed on a shared directory in our computing cluster and I am thinking this may be where my issue is stemming from.  Whipped will parse through the GTF, build splice graphs, and then error out when attempting to open graphs.jls.  There is no such file that I can see at the location specified.  Is this a graph file whippet is attempting to build?  And if so, I am guessing it is run-specific, such that having it installed in a central directory may be where the permissions error is arising from? 

```
Building Splice Graphs for NW_004988083.1..
Building Splice Graphs for NW_004988085.1..
Building Splice Graphs for NW_004988091.1..
Building Splice Graphs for NW_004988092.1..
Building full sg-index..
 21.304731 seconds (92.10 M allocations: 1.668 GB, 2.53% gc time)
Building edges..
  2.476774 seconds (15.05 M allocations: 741.651 MB, 27.10% gc time)
469.058015 seconds (209.30 M allocations: 219.158 GB, 39.50% gc time)
469.136506 seconds (209.31 M allocations: 219.159 GB, 39.49% gc time)
Serializing splice graph index...
warning: parsing line table prologue at 0x0001cd5c should have ended at 0x0001d0f0 but it ended at 0x0001ce35
warning: parsing line table prologue at 0x0000e1c8 should have ended at 0x0000e52f but it ended at 0x0000e294
warning: parsing line table prologue at 0x00003c27 should have ended at 0x00003ffc but it ended at 0x00003cf3
warning: parsing line table prologue at 0x0000a9c0 should have ended at 0x0000ace8 but it ended at 0x0000aa8c
warning: parsing line table prologue at 0x0001357a should have ended at 0x0001390c but it ended at 0x00013646
warning: parsing line table prologue at 0x00007565 should have ended at 0x00007914 but it ended at 0x00007631
ERROR: LoadError: SystemError: opening file /mnt/lustre/software/anaconda/colsa/envs/whippet-0.8/local/src/Whippet.jl/bin/../index/graph.jls: Permission denied
 in #systemerror#51 at ./error.jl:34 [inlined]
 in systemerror(::String, ::Bool) at ./error.jl:34
 in open(::String, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./iostream.jl:89
 in open(::String, ::String) at ./iostream.jl:101
 in open(::##2#4, ::String, ::String) at ./iostream.jl:111
 in main() at /mnt/lustre/software/anaconda/colsa/envs/whippet-0.8/local/src/Whippet.jl/bin/whippet-index.jl:80
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
while loading /mnt/lustre/software/anaconda/colsa/envs/whippet-0.8/local/src/Whippet.jl/bin/whippet-index.jl, in expression starting on line 86
```

**Comment by timbitz** [comment]
Hi @AndrewLangvt,  Did you run the executable with `-h` flag to see the available options?  

One of them `--index` is indeed to specify the output prefix of the graph you are building..  I would suggest using it to specify a directory/prefix that you have writable access to (it seems you do not have permission to write to `Whippet.jl/index/`).  By default it outputs to `Whippet.jl/index/graph` and adds the `.jls`.  So you will want to exclude the `.jls` from what you supply to this option, e.g. `--index some/path/you/have/access/to/graph_name_or_genome_build`

I will try to think of how best to improve the documentation for these sorts of situations.

**Comment by AndrewLangvt** [comment]
Thanks for the quick reply @timbitz.  I feel rather silly now.  I did not run with the `-h` flag; I was just following through the walk-through directions here on GitHub.  I'll be sure to dig into each command more thoroughly in the future, recognizing that the documentation may not have all of the flags laid out within.  I appreciate the help, specifying the index location did the trick!

**Comment by timbitz** [comment]
Hi @AndrewLangvt, Yah my apologies for that. The walk-through directions were meant to be simple and illustrate Whippet's ease-of-use with default parameters, which should be suitable for the vast majority of users.  However, that inadvertently made it less intuitive to use for those who require the non-default parameters, which have not all been sufficiently documented perhaps.

I have added a tad bit of rough documentation (to master) in the walk-through directions for non-default names & locations of whippet indexes and to point users to the command line flags.  However perhaps this is still lacking a tad, and I should really add a separate section that goes into more detail on each parameter.  I will think about the best way to do this while still maintaining the base simplicity of the docs.
