### ISSUE TITLE
Not showing concordance with other tools, can we manually normalize?

### ISSUE THREAD

**Issue by seyfim** [timbitz/Whippet.jl#70]
Hello,

My current research involves implementing alternative splicing software to identify candidate genes for downstream analysis. Currently, I have implemented MAJIQ, rMATS and your tool. While we see 40-60% concordance between MAJIQ and rMATS, we are seeing < 6% with those tools and Whippet.  We also had another tool that was transcript based, Kallisto, and in order to see concordance with other transcript based tools I had to implement upper quartile normalization on the Raw Read counts before continuing DE analysis. 

Will normalizing the Raw_Reads column  in the .gene.tpm files (generated from Whippet Quant) affect/influence the delta psi calculation?

**Comment by timbitz** [comment]
Hi @seyfim, reporting of "issues" for this repository are reserved for actual software bugs, and are not the intended forum for questions on program usage, command line options, and output interpretation.  For this we ask that you use the gitter chat, or you can e-mail me directly tim.sterne.weiler@utoronto.ca and I would be more than happy to try and help.

To quickly answer your question though: No, nothing in the .tpm file will affect deltaPsi calculations.  However, altering the significance and filtering criteria for deltaPsi could definitely make a difference.. As could ensuring that you are intersecting the coordinates from Whippet with other programs correctly (Whippet "nodes" vs. "exons" are often not directly comparable, please see the README.md for info on this).

**Comment by mirimia** [comment]
Hi Tim and @seyfim,

Sorry to comment on this closed issue, but I’m quite interested on this topic too. If you email about it, please CC me if you don’t mind (mirimia@gmail.com). 

Thanks

**Comment by timbitz** [comment]
Hey @mirimia! I will CC you if I get an e-mail, and am happy to re-open the issue if it turns out to be related to a bug that I can fix.
