### ISSUE TITLE
working with fa files

### ISSUE THREAD

**Issue by jordi-vaquero** [timbitz/Whippet.jl#84]
Is whippet working with fa files instead of fastq? I have a set of files that doesn't contain quality string, and the following error appears
` [1] _read!(::BioSequences.FASTQ.Reader, ::BioCore.Ragel.State{BufferedStreams.BufferedInputStream{BufferedStreams.BufferedInputStream{Libz.Source{:inflate,BufferedStreams.BufferedInputStream{IOStream}}}}}, ::BioSequences.FASTQ.Record) at /home/jordi/.julia/v0.6/BioCore/src/ReaderHelper.jl:164`
`[2] read! at /home/jordi/.julia/v0.6/BioCore/src/ReaderHelper.jl:134 [inlined]`
` [3] read! at /home/jordi/.julia/v0.6/Whippet/src/record.jl:11 [inlined]`
` [4] read_chunk! at /home/jordi/.julia/v0.6/Whippet/src/reads.jl:17 [inlined]`
` [5] #process_paired_reads!#62(::Int64, ::Bool, ::Int64, ::Requests.ResponseStream{TCPSocket}, ::Requests.ResponseStream{TCPSocket}, ::Bool, ::Function, ::BioSequences.FASTQ.Reader, ::BioSequences.FASTQ.Reader, ::Whippet.AlignParam, ::Whippet.GraphLib, ::Whippet.GraphLibQuant{Whippet.SGAlignPaired,Whippet.DefaultCounter}, ::Whippet.MultiMapping{Whippet.SGAlignPaired,Whippet.DefaultCounter}, ::Whippet.DefaultBiasMod) at /home/jordi/.julia/v0.6/Whippet/src/reads.jl:151`
 `[6] (::Whippet.#kw##process_paired_reads!)(::Array{Any,1}, ::Whippet.#process_paired_reads!, ::BioSequences.FASTQ.Reader, ::BioSequences.FASTQ.Reader, ::Whippet.AlignParam, ::Whippet.GraphLib, ::Whippet.GraphLibQuant{Whippet.SGAlignPaired,Whippet.DefaultCounter}, ::Whippet.MultiMapping{Whippet.SGAlignPaired,Whippet.DefaultCounter}, ::Whippet.DefaultBiasMod) at ./<missing>:0`
` [7] macro expansion at /home/jordi/.julia/v0.6/Whippet/src/timer.jl:5 [inlined]`
 `[8] main() at /home/jordi/.julia/v0.6/Whippet/bin/whippet-quant.jl:169`
 `[9] include_from_node1(::String) at ./loading.jl:576`
 `[10] include(::String) at ./sysimg.jl:14`
 `[11] process_options(::Base.JLOptions) at ./client.jl:305`
 `[12] _start() at ./client.jl:371`
`while loading /home/jordi/.julia/v0.6/Whippet/bin/whippet-quant.jl, in expression starting on line 5`

**Comment by timbitz** [comment]
Whippet does not work with FASTA only FASTQ-- it's alignment algorithm utilizes the quality scores.
