### ISSUE TITLE
There's an additional column in the output files

### ISSUE THREAD

**Issue by aleighbrown** [timbitz/Whippet.jl#88]
FYI:

Appears that output files have a tab at the end which makes R, probably python pandas too haven't tried, think there's an additional column of NA. Very small problem, just letting you know

Isoform`\t`TpM`\t`Read_Counts`\n`
ENSMUST00000158976`\t`0.0`\t`0.0`\t\n`

Not 100% on this, but I'm thinking this caused by the use of tab_write in the io.jl script for the last values....

**Comment by timbitz** [comment]
Good catch, Thanks!.  I think it is only the `.tpm` files that are printed from `output_tpm()` at the end of `src/quant.jl`.  If you see any other files that have this let me know, but I think those are the only ones -- I'll fix next update.
