### ISSUE TITLE
can I use .tpm.gz files to perform gene/transcript differential expression analysis?

### ISSUE THREAD

**Issue by JamalEH** [timbitz/Whippet.jl#91]
Hi,

Can I perform differential expression analysis at gene and isoform level using DESeq2 on the count matrix from the .tpm.gz files generated by whippet? Can you also please tell me how the counts are calculated, based on junction reads?

Thank you in advance!
Best regards,
Jamal.

**Comment by timbitz** [comment]
Yes you can use the counts with DESeq.  The .tpm.gz files are calculated using EM across annotated transcripts with all reads, that is exon-body and junction reads.

**Comment by timbitz** [comment]
Also this info is in the paper -- https://doi.org/10.1016/j.molcel.2018.08.018
